Repository DSC-JSS-NOIDA/HackHive, pull requests merged in 2024-05, with the labels that each got.

#24 Footer Design and Fixing broken link to Hackathon Page #6
  frontend/src/assets/copyright_icon.svg
  frontend/src/assets/facebook_icon.svg
  frontend/src/assets/instagram_icon.svg
  frontend/src/assets/linkedin_icon.svg
  frontend/src/assets/twitter_icon.svg
  frontend/src/assets/whatsapp_icon.svg
  frontend/src/components/FeaturedHackathons/FeaturedHackathons.jsx
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/HackathonCard/HackathonCard.jsx
  frontend/tailwind.config.js
Labels: GSSoC'24, level2

#26 created the code of conduct file
  Code_of_Conduct.md
Labels: level 1

#36 Migrate Normal Css to Tailwind classes #5
  frontend/index.html
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Searchbar/Search.css
  frontend/src/components/Searchbar/Search.jsx
  frontend/src/index.css
Labels: gssoc, level 2

#30 Styled Leading organization component
  frontend/src/components/Organizations/Organizations.css
  frontend/src/components/Organizations/Organizations.jsx
Labels: gssoc, level 1

#83 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level1

#73 ADD: pre-commit hooks for linting
  frontend/.husky/pre-commit
  frontend/package-lock.json
  frontend/package.json
Labels: gssoc, level1

#86 Docs: Added frontend project getting starting instructions in README.md
  README.md
Labels: gssoc, level1

#89 Create greeting.yaml
  .github/workflows/greeting.yaml
Labels: gssoc, level1

#100 Configured prettier and Configured prettier with lint-staged
  frontend/.prettierignore
  frontend/.prettierrc
  frontend/package.json
Labels: gssoc, level1

#118 Styling of the articles in the Blog Page
  frontend/package-lock.json
  frontend/src/components/Post/Post.jsx
Labels: gssoc, level2

#119 Hackathon cards UI improved.
  frontend/src/components/FeaturedHackathons/FeaturedHackathons.jsx
  frontend/src/components/HackathonCard/HackathonCard.jsx
Labels: gssoc, level2

#116 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, level1

#105 Update README.md
  README.md
Labels: gssoc, level1

#88 Updated UI of Scrollbar
  frontend/src/index.css
Labels: gssoc, level1

#127 [Feature] Added Custom 404 page
  frontend/src/App.jsx
  frontend/src/Pages/Custom404.jsx
  frontend/src/assets/bg.jpg
  frontend/src/assets/logo.png
  frontend/tailwind.config.js
Labels: gssoc, level1

#128 Fixes: Website not responsive #101
  frontend/src/Pages/Blog.jsx
  frontend/src/Pages/Login.jsx
  frontend/src/components/FeaturedHackathons/FeaturedHackathons.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/HackathonCard/HackathonCard.jsx
  frontend/src/components/HeadingSection/HeadingSection.jsx
  frontend/src/components/HeroSection/Hero.css
  frontend/src/components/HeroSection/Hero.jsx
  frontend/src/components/LoginCard/LoginCard.jsx
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/Organizations/Organizations.jsx
  frontend/src/components/Searchbar/Search.jsx
  frontend/src/index.css
Labels: gssoc, level3
